"""Order routing and risk adjustments for trade signals."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol


class ExchangeClient(Protocol):
    """Minimal interface for submitting orders to an exchange."""

    def create_order(self, *, symbol: str, side: str, quantity: float, price: float | None = None) -> dict:
        ...


@dataclass
class OrderIntent:
    """Represents a desired trade action generated by a strategy."""

    symbol: str
    side: str
    quantity: float
    price: float | None = None


class OrderRouter:
    """Apply risk checks and dispatch intents to the exchange."""

    def __init__(self, client: ExchangeClient) -> None:
        self._client = client

    def submit(self, intent: OrderIntent) -> dict:
        """Submit an order after applying basic sanity checks."""

        if intent.quantity <= 0:
            raise ValueError("Order quantity must be positive")

        return self._client.create_order(
            symbol=intent.symbol,
            side=intent.side,
            quantity=intent.quantity,
            price=intent.price,
        )
